name: ci

on:
  pull_request:
    branches:
      - '**'
  push:
    branches:
      - main
  schedule:
    - cron:  '45 4 * * *'

env:
  CI: true

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Garnet Runtime Visibility
        uses: garnet-org/action@c747ff1f597c84579e10173301a31c30bb815181 # v2.3.0-rc.1
        with:
          api_token: ${{ secrets.GARNET_API_TOKEN }}
      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y ripgrep graphviz wamerican
      - uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
      - run: bundle exec rake sorbet
      - run: bundle exec rake rubocop_ci
      - run: bundle exec rake test
